# Generated by Django 5.1.6 on 2025-02-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_initial_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credits_remaining',
            field=models.IntegerField(),
        ),
    ]
