# Generated by Django 5.1.6 on 2025-02-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_credits_remaining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='oauth_id',
            new_name='google_id',
        ),
    ]
